#include "automation/commands.hpp"
#include "core/copy_array.hpp"
namespace sketchy {
namespace {
QJsonObject number() { return {{"type", "number"}}; }
QJsonObject modelStyleSchema() {
    const QJsonObject rgb{{"type", "array"}, {"minItems", 3}, {"maxItems", 3},
                          {"items", QJsonObject{{"type", "number"}, {"minimum", 0}, {"maximum", 1}}}};
    const QJsonObject flag{{"type", "boolean"}};
    const QJsonObject properties{
        {"mode", QJsonObject{{"type", "string"}, {"enum", QJsonArray{"textured", "shaded", "monochrome", "wireframe", "xray"}}}},
        {"background", rgb}, {"ground", rgb}, {"front", rgb}, {"back", rgb}, {"edge", rgb},
        {"groundVisible", flag}, {"gridVisible", flag}, {"axesVisible", flag}, {"edgesVisible", flag}, {"profiles", flag},
        {"groundHeight", QJsonObject{{"type", "number"}, {"minimum", -1e6}, {"maximum", 1e6}}},
        {"profileWidth", QJsonObject{{"type", "number"}, {"minimum", 1}, {"maximum", 8}}},
        {"xrayOpacity", QJsonObject{{"type", "number"}, {"minimum", .01}, {"maximum", .95}}}};
    QJsonArray required;
    for (const auto &name : properties.keys()) required.append(name);
    return {{"type", "object"}, {"properties", properties}, {"required", required}, {"additionalProperties", false}};
}
QJsonObject stableId(bool zero = false) {
    return {{"type", "string"},
            {"pattern", zero ? "^(0|[1-9][0-9]*)$" : "^[1-9][0-9]*$"},
            {"maxLength", 20},
            {"description", "Canonical uint64 decimal string"}};
}
QJsonObject list(QJsonObject items, int minimum, int maximum) {
    return {{"type", "array"}, {"items", items}, {"minItems", minimum}, {"maxItems", maximum}};
}
QJsonObject targetsSchema() {
    return list(
        QJsonObject{{"type", "object"},
                    {"properties",
                     QJsonObject{{"body", stableId()},
                                 {"entity", stableId(true)},
                                 {"kind", QJsonObject{{"type", "string"},
                                                      {"enum", QJsonArray{"context", "face", "edge",
                                                                          "vertex", "guide"}}}}}},
                    {"required", QJsonArray{"body", "kind", "entity"}},
                    {"additionalProperties", false}},
        1, 10000);
}
QJsonObject spec(QString name, QString label, QString category, QJsonObject properties,
                 QJsonArray required) {
    properties["command"] = QJsonObject{{"const", name}};
    required.append("command");
    return {{"name", name},
            {"label", label},
            {"category", category},
            {"parameters", QJsonObject{{"$schema", "https://json-schema.org/draft/2020-12/schema"},
                                       {"type", "object"},
                                       {"description", label},
                                       {"properties", properties},
                                       {"required", required},
                                       {"additionalProperties", false}}},
            {"validation", "Schema plus authoritative geometry, document and resource validation"},
            {"undo", "one batch history item"}};
}
QJsonObject edgeAppearanceSpec() {
    auto entry = spec(
        "geometry.edge_appearance", "Set independent edge hide, soften and smooth flags",
        "Geometry",
        {{"context", stableId(true)},
         {"entities",
          list(QJsonObject{{"type", "object"},
                           {"properties", QJsonObject{{"body", stableId()}, {"edge", stableId()}}},
                           {"required", QJsonArray{"body", "edge"}},
                           {"additionalProperties", false}},
               1, 4096)},
         {"hidden", QJsonObject{{"type", "boolean"}}},
         {"soft", QJsonObject{{"type", "boolean"}}},
         {"smooth", QJsonObject{{"type", "boolean"}}}},
        {"context", "entities"});
    auto parameters = entry["parameters"].toObject();
    parameters["minProperties"] = 4; // command, context, entities, at least one flag.
    entry["parameters"] = parameters;
    return entry;
}
QJsonObject textureMappingSpec(const QJsonObject &point, const QJsonObject &space) {
    auto object = [](QJsonObject properties, QJsonArray required) {
        return QJsonObject{{"type", "object"}, {"properties", properties},
                           {"required", required}, {"additionalProperties", false}};
    };
    const auto repeats = list(QJsonObject{{"type", "number"}, {"minimum", -1e9},
                                          {"maximum", 1e9}}, 2, 2);
    const auto vector = list(number(), 3, 3);
    const QJsonObject size{
        {"description", "Signed repeat size in metres; a negative size mirrors that axis"},
        {"oneOf", QJsonArray{
            QJsonObject{{"type", "number"}, {"minimum", 1e-6}, {"maximum", 1e6}},
            QJsonObject{{"type", "number"}, {"minimum", -1e6}, {"maximum", -1e-6}}}}};
    const auto planar = object(
        {{"type", QJsonObject{{"const", "planar"}}}, {"origin", point},
         {"normal", vector}, {"tangent", vector}, {"width", size}, {"height", size},
         {"rotationRadians", number()}, {"offset", repeats}},
        {"type", "origin", "normal", "tangent", "width", "height"});
    const auto pins = object(
        {{"type", QJsonObject{{"const", "pins"}}}, {"points", list(point, 3, 3)},
         {"coordinates", list(repeats, 3, 3)}}, {"type", "points", "coordinates"});
    const auto gradient = list(QJsonObject{{"type", "number"}, {"minimum", -1e9},
                                           {"maximum", 1e9}}, 3, 3);
    const auto affine = object(
        {{"type", QJsonObject{{"const", "affine"}}}, {"origin", point},
         {"uGradient", gradient}, {"vGradient", gradient}, {"offset", repeats}},
        {"type", "origin", "uGradient", "vGradient", "offset"});
    return spec(
        "material.map_texture", "Set or reset a face texture projection in metres/radians",
        "Materials",
        {{"body", stableId()}, {"face", stableId()},
         {"side", QJsonObject{{"type", "string"},
                               {"enum", QJsonArray{"front", "back", "both"}}}},
         {"space", space},
         {"projection", QJsonObject{
             {"description", "Null restores implicit mapping on the chosen side(s); UVs are unwrapped repeats with a top-left origin and +V down"},
             {"oneOf", QJsonArray{QJsonObject{{"type", "null"}}, planar, pins, affine}}}}},
        {"body", "face", "side", "space", "projection"});
}
} // namespace
QJsonArray commandCatalog() {
    auto coordinate = QJsonObject{
        {"type", "number"}, {"minimum", -coordinateLimit}, {"maximum", coordinateLimit}};
    auto point = list(coordinate, 3, 3);
    const QJsonObject space{{"type", "string"}, {"enum", QJsonArray{"local", "world"}}};
    auto affine = list(number(), 16, 16);
    affine["description"] = "Column-major affine 4x4. Translation is at indices 12, 13, 14. "
                            "Transform only inspected vertex IDs to preserve member thickness; "
                            "uniform bounds scaling changes thickness.";
    return {
        spec("assert.measurement", "Require a final batch measurement to match", "Verification",
             {{"body", stableId()}, {"space", space},
              {"metric", QJsonObject{{"type", "string"},
                  {"enum", QJsonArray{"length", "area", "volume", "dimensions", "minimum", "maximum"}}}},
              {"expected", QJsonObject{{"oneOf", QJsonArray{number(), list(number(), 3, 3)}}}},
              {"tolerance", QJsonObject{{"type", "number"}, {"minimum", 0}, {"maximum", 1},
                  {"description", "Explicit absolute tolerance in m, m2 or m3; bounds compare each axis"}}}},
             {"body", "space", "metric", "expected", "tolerance"}),
        spec("document.style", "Change model style", "Document",
             {{"style", modelStyleSchema()}}, {"style"}),
        spec("document.units", "Change document units", "Document",
             {{"units", QJsonObject{{"type", "string"}, {"enum", QJsonArray{"m", "mm", "ft-in"}}}}},
             {"units"}),
        spec("tag.create", "Create tag or folder", "Organization",
             {{"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"parent", stableId(true)},
              {"folder", QJsonObject{{"type", "boolean"}}}},
             {"name"}),
        spec("tag.edit", "Rename, move or show tag", "Organization",
             {{"tag", stableId()},
              {"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"parent", stableId(true)},
              {"visible", QJsonObject{{"type", "boolean"}}}},
             {"tag"}),
        spec("tag.delete", "Delete unused tag or empty folder", "Organization",
             {{"tag", stableId()}}, {"tag"}),
        spec("tag.assign", "Assign entity tag", "Organization",
             {{"body", stableId()}, {"tag", stableId(true)}}, {"body", "tag"}),
        spec("scene.rename", "Rename entity", "Scene",
             {{"body", stableId()}, {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"body", "name"}),
        spec("guide.point", "Create guide point", "Guides",
             {{"body", stableId(true)}, {"space", space}, {"origin", point}}, {"body", "origin"}),
        spec("guide.line", "Create guide line", "Guides",
             {{"body", stableId(true)}, {"space", space}, {"origin", point}, {"direction", point}},
             {"body", "origin", "direction"}),
        spec("guide.angle", "Create angled guide", "Guides",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"angle", number()}},
             {"body", "origin", "normal", "xAxis", "angle"}),
        spec("guide.offset", "Offset guide line", "Guides",
             {{"body", stableId()},
              {"space", space},
              {"guide", stableId()},
              {"normal", point},
              {"distance", number()}},
             {"body", "guide", "normal", "distance"}),
        spec("guide.erase", "Delete guide", "Guides", {{"body", stableId()}, {"guide", stableId()}},
             {"body", "guide"}),
        spec("guide.clear", "Delete guides in context or document", "Guides",
             {{"body", stableId(true)}}, {"body"}),
        spec("assembly.site_place", "Place an existing context with explicit units, frame and yaw delta", "Recipes",
             {{"body",stableId()},
              {"position",list(QJsonObject{{"type","number"},{"minimum",-1e12},{"maximum",1e12}},3,3)},
              {"positionUnit",QJsonObject{{"type","string"},{"enum",QJsonArray{"m","mm","cm","in","ft"}}}},
              {"frame",QJsonObject{{"type","string"},{"enum",QJsonArray{"world","parent"}}}},
              {"yawDeltaRadians",QJsonObject{{"type","number"},{"minimum",-6.283185307179586},{"maximum",6.283185307179586}}}},
             {"body","position","positionUnit","frame","yawDeltaRadians"}),
        spec("assembly.table", "Create an editable table with four shared component legs", "Recipes",
             {{"width", QJsonObject{{"type","number"},{"minimum",.3},{"maximum",5},{"default",1.2}}},
              {"depth", QJsonObject{{"type","number"},{"minimum",.3},{"maximum",5},{"default",.8}}},
              {"height", QJsonObject{{"type","number"},{"minimum",.3},{"maximum",3},{"default",.75}}},
              {"topThickness", QJsonObject{{"type","number"},{"minimum",.01},{"maximum",.2},{"default",.04}}},
              {"legSize", QJsonObject{{"type","number"},{"minimum",.02},{"maximum",.3},{"default",.05}}},
              {"legInset", QJsonObject{{"type","number"},{"minimum",0},{"maximum",.5},{"default",.06}}},
              {"origin",point}}, {}),
        spec("assembly.cabinet", "Create an editable open cabinet with shared side and shelf panels", "Recipes",
             {{"width", QJsonObject{{"type","number"},{"minimum",.3},{"maximum",5},{"default",.9}}},
              {"depth", QJsonObject{{"type","number"},{"minimum",.2},{"maximum",3},{"default",.4}}},
              {"height", QJsonObject{{"type","number"},{"minimum",.3},{"maximum",5},{"default",1.2}}},
              {"panelThickness", QJsonObject{{"type","number"},{"minimum",.01},{"maximum",.1},{"default",.018}}},
              {"shelves", QJsonObject{{"type","integer"},{"minimum",0},{"maximum",6},{"default",2}}},
              {"origin",point}}, {}),
        spec("assembly.stairs", "Create an editable solid straight stair flight", "Recipes",
             {{"stepCount", QJsonObject{{"type", "integer"}, {"minimum", 2}, {"maximum", 32}, {"default", 12}}},
              {"width", QJsonObject{{"type", "number"}, {"minimum", .4}, {"maximum", 5}, {"default", 1}}},
              {"totalRise", QJsonObject{{"type", "number"}, {"minimum", .2}, {"maximum", 10}, {"default", 2.4}}},
              {"going", QJsonObject{{"type", "number"}, {"minimum", .1}, {"maximum", 1}, {"default", .28}}},
              {"origin", point}}, {}),
        spec("assembly.roof", "Create an editable gable roof with explicit vertical thickness", "Recipes",
             {{"width", QJsonObject{{"type", "number"}, {"minimum", 2}, {"maximum", 100}, {"default", 6}}},
              {"depth", QJsonObject{{"type", "number"}, {"minimum", 2}, {"maximum", 100}, {"default", 4}}},
              {"plateHeight", QJsonObject{{"type", "number"}, {"minimum", .5}, {"maximum", 20}, {"default", 2.7}}},
              {"pitchDegrees", QJsonObject{{"type", "number"}, {"minimum", 5}, {"maximum", 75}, {"default", 30}}},
              {"overhang", QJsonObject{{"type", "number"}, {"minimum", 0}, {"maximum", 2}, {"default", .3}}},
              {"verticalThickness", QJsonObject{{"type", "number"}, {"minimum", .02}, {"maximum", 1}, {"default", .15}}},
              {"origin", point}}, {}),
        spec("assembly.room", "Create a room with hosted reusable window assemblies", "Recipes",
             {{"width", QJsonObject{{"type", "number"}, {"minimum", 2}, {"maximum", 100}}},
              {"depth", QJsonObject{{"type", "number"}, {"minimum", 2}, {"maximum", 100}}},
              {"height", QJsonObject{{"type", "number"}, {"minimum", 1}, {"maximum", 10}}},
              {"wallThickness", QJsonObject{{"type", "number"}, {"minimum", .05}, {"maximum", 1}}},
              {"windowWidth", QJsonObject{{"type", "number"}, {"minimum", .3}, {"maximum", 10}}},
              {"windowHeight", QJsonObject{{"type", "number"}, {"minimum", .3}, {"maximum", 5}}},
              {"sill", QJsonObject{{"type", "number"}, {"minimum", .05}, {"maximum", 5}}},
              {"memberThickness",
               QJsonObject{{"type", "number"}, {"minimum", .01}, {"maximum", .5}}},
              {"frameDepth", QJsonObject{{"type", "number"}, {"minimum", .01}, {"maximum", 1}}}},
             {}),
        spec("assembly.room.adopt_hosted", "Adopt explicit authored room host relationships", "Recipes",
             {{"body", stableId()}}, {"body"}),
        spec("assembly.window.resize", "Resize one authored window and its host opening", "Recipes",
             {{"body", stableId()},
              {"width", QJsonObject{{"type", "number"}, {"minimum", .3}, {"maximum", 10}}},
              {"scope", QJsonObject{{"const", "instance"}}}},
             {"body", "width", "scope"}),
        spec("geometry.face", "Draw face", "Geometry",
             {{"loops", list(list(point, 3, 10000), 1, 10000)},
              {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"loops"}),
        spec("geometry.insert_edges", "Insert planar edges and form faces", "Geometry",
             {{"body", stableId(true)},
              {"origin", point},
              {"normal", point},
              {"edges", list(list(point, 2, 2), 1, 1024)}},
             {"body", "origin", "normal", "edges"}),
        spec("geometry.rectangle", "Draw rectangle on plane", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"width", number()},
              {"height", number()}},
             {"body", "origin", "normal", "xAxis", "width", "height"}),
        spec("geometry.polygon", "Draw regular polygon", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"sides", QJsonObject{{"type", "integer"}, {"minimum", 3}, {"maximum", 256}}}},
             {"body", "origin", "normal", "xAxis", "radius", "sides"}),
        spec("geometry.polyline", "Draw sampled polyline", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"points", list(point, 2, 512)},
              {"closed", QJsonObject{{"type", "boolean"}}}},
             {"body", "origin", "normal", "points", "closed"}),
        spec("geometry.circle", "Draw circle", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 3}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "segments"}),
        spec("geometry.arc_center", "Draw center arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"startAngle", number()},
              {"sweepAngle", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "startAngle", "sweepAngle",
              "segments"}),
        spec("geometry.arc_two_points", "Draw two-point arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"start", point},
              {"end", point},
              {"normal", point},
              {"bulge", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "start", "end", "normal", "bulge", "segments"}),
        spec("geometry.arc_three_points", "Draw three-point arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"start", point},
              {"through", point},
              {"end", point},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "start", "through", "end", "segments"}),
        spec("geometry.pie", "Draw pie sector", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"startAngle", number()},
              {"sweepAngle", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 2}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "startAngle", "sweepAngle",
              "segments"}),
        spec("geometry.wire", "Draw loose edge", "Geometry",
             {{"body", stableId(true)}, {"start", point}, {"end", point}},
             {"body", "start", "end"}),
        spec("geometry.split_edge", "Split edge", "Geometry",
             {{"body", stableId()},
              {"edge", stableId()},
              {"fraction",
               QJsonObject{{"type", "number"}, {"exclusiveMinimum", 0}, {"exclusiveMaximum", 1}}}},
             {"body", "edge", "fraction"}),
        spec("geometry.erase_face", "Erase face, retain boundary", "Geometry",
             {{"body", stableId()}, {"face", stableId()}}, {"body", "face"}),
        spec("geometry.erase_edge", "Erase edge or join coplanar faces", "Geometry",
             {{"body", stableId()}, {"edge", stableId()}}, {"body", "edge"}),
        spec("geometry.heal_face", "Heal closed planar region", "Geometry",
             {{"body", stableId()}, {"edge", stableId()}, {"origin", point}, {"normal", point}},
             {"body", "edge", "origin", "normal"}),
        spec("geometry.cleanup", "Merge coincident topology", "Geometry", {{"body", stableId()}},
             {"body"}),
        spec("geometry.offset",
             "Offset face boundaries (positive outward, negative inward; preserves source coverage "
             "and holes)",
             "Geometry",
             {{"body", stableId()}, {"face", stableId()}, {"distance", number()}, {"space", space}},
             {"body", "face", "distance"}),
        edgeAppearanceSpec(),
        spec("geometry.reverse_faces", "Reverse selected faces; preserve physical-side materials",
             "Geometry",
             {{"context", stableId(true)},
              {"entities",
               QJsonObject{{"type", "array"},
                           {"minItems", 1},
                           {"maxItems", 4096},
                           {"items", QJsonObject{{"type", "object"},
                                                 {"properties", QJsonObject{{"body", stableId()},
                                                                            {"face", stableId()}}},
                                                 {"required", QJsonArray{"body", "face"}},
                                                 {"additionalProperties", false}}}}}},
             {"context", "entities"}),
        spec("geometry.orient_faces",
             "Orient connected faces to a reference face; preserve physical-side materials",
             "Geometry", {{"context", stableId(true)}, {"body", stableId()}, {"face", stableId()}},
             {"context", "body", "face"}),
        spec("geometry.boolean",
             "Combine two editable solids; explicitly retain or consume operands", "Geometry",
             {{"body", stableId()},
              {"tool", stableId()},
              {"context", stableId(true)},
              {"operation", QJsonObject{{"type", "string"},
                                        {"enum", QJsonArray{"union", "subtract", "intersection"}}}},
              {"keepOperands", QJsonObject{{"type", "boolean"}}}},
             {"body", "tool", "context", "operation", "keepOperands"}),
        spec("geometry.trim", "Trim target while always retaining the cutting tool", "Geometry",
             {{"body", stableId()},
              {"tool", stableId()},
              {"context", stableId(true)},
              {"keepTarget", QJsonObject{{"type", "boolean"}}}},
             {"body", "tool", "context", "keepTarget"}),
        spec("geometry.split", "Partition two solids into target, tool and overlap regions",
             "Geometry",
             {{"body", stableId()},
              {"tool", stableId()},
              {"context", stableId(true)},
              {"keepOperands", QJsonObject{{"type", "boolean"}}}},
             {"body", "tool", "context", "keepOperands"}),
        spec("geometry.outer_shell",
             "Union solids and fill enclosed cavities; retain exterior through-holes", "Geometry",
             {{"body", stableId()},
              {"tool", stableId()},
              {"context", stableId(true)},
              {"keepOperands", QJsonObject{{"type", "boolean"}}}},
             {"body", "tool", "context", "keepOperands"}),
        spec("geometry.intersect", "Insert intersection edges into explicit target faces",
             "Geometry",
             {{"context", stableId(true)},
              {"mode", QJsonObject{{"type", "string"},
                                   {"enum", QJsonArray{"selected", "context", "model"}}}},
              {"entities",
               QJsonObject{{"type", "array"},
                           {"minItems", 1},
                           {"maxItems", 128},
                           {"items", QJsonObject{{"type", "object"},
                                                 {"properties", QJsonObject{{"body", stableId()},
                                                                            {"face", stableId()}}},
                                                 {"required", QJsonArray{"body", "face"}},
                                                 {"additionalProperties", false}}}}}},
             {"context", "mode", "entities"}),
        spec(
            "geometry.sweep", "Sweep a profile into a separate solid; retain source profile",
            "Geometry",
            {{"body", stableId()},
             {"face", stableId()},
             {"path",
              QJsonObject{{"type", "array"}, {"items", point}, {"minItems", 2}, {"maxItems", 129}}},
             {"closed", QJsonObject{{"type", "boolean"}, {"default", false}}},
             {"space", space}},
            {"body", "face", "path"}),
        spec("geometry.push_pull", "Push/pull selected face", "Geometry",
             {{"body", stableId()},
              {"face", stableId()},
              {"distance", number()},
              {"newFace", QJsonObject{{"type", "boolean"}, {"default", false}}}},
             {"body", "face", "distance"}),
        spec("geometry.extrude_isolated", "Extrude isolated face", "Geometry",
             {{"body", stableId()}, {"face", stableId()}, {"distance", number()}},
             {"body", "face", "distance"}),
        spec("geometry.transform_selection", "Transform selected geometry", "Geometry",
             {{"entities", targetsSchema()},
              {"matrix", affine},
              {"pivot", point},
              {"space", space},
              {"copy", QJsonObject{{"type", "boolean"}, {"default", false}}}},
             {"entities", "matrix"}),
        spec("geometry.array_selection", "Linear or radial copy array", "Geometry",
             {{"entities", targetsSchema()},
              {"mode", QJsonObject{{"type", "string"}, {"enum", QJsonArray{"linear", "radial"}}}},
              {"count", QJsonObject{{"type", "integer"},
                                    {"minimum", 1},
                                    {"maximum", int(maxArrayCopies)},
                                    {"description",
                                     "New copies; total instances including source = count + 1"}}},
              {"delta", point},
              {"axis", point},
              {"angle", number()},
              {"pivot", point},
              {"space", space},
              {"divide",
               QJsonObject{
                   {"type", "boolean"},
                   {"default", false},
                   {"description",
                    "Divide displacement or sweep into count intervals, including endpoint"}}}},
             {"entities", "mode", "count"}),
        spec("geometry.translate", "Move selection", "Geometry",
             {{"body", stableId()}, {"delta", point}}, {"body", "delta"}),
        spec(
            "geometry.erase_selection", "Delete selected entities", "Geometry",
            {{"context", stableId(true)},
             {"showHidden", QJsonObject{{"type", "boolean"}}},
             {"entities",
              list(
                  QJsonObject{
                      {"type", "object"},
                      {"properties",
                       QJsonObject{{"body", stableId()},
                                   {"kind", QJsonObject{{"type", "string"},
                                                        {"enum", QJsonArray{"context", "face",
                                                                            "edge", "guide"}}}},
                                   {"entity", stableId(true)}}},
                      {"required", QJsonArray{"body", "kind", "entity"}},
                      {"additionalProperties", false}},
                  1, 10000)}},
            {"entities"}),
        spec(
            "group.selection", "Make group from selected entities", "Scene",
            {{"context", stableId(true)},
             {"showHidden", QJsonObject{{"type", "boolean"}}},
             {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}},
             {"entities",
              list(
                  QJsonObject{
                      {"type", "object"},
                      {"properties",
                       QJsonObject{{"body", stableId()},
                                   {"kind", QJsonObject{{"type", "string"},
                                                        {"enum", QJsonArray{"context", "face",
                                                                            "edge", "guide"}}}},
                                   {"entity", stableId(true)}}},
                      {"required", QJsonArray{"body", "kind", "entity"}},
                      {"additionalProperties", false}},
                  1, 10000)}},
            {"entities"}),
        spec(
            "component.selection", "Make component from selected entities", "Scene",
            {{"context", stableId(true)},
             {"showHidden", QJsonObject{{"type", "boolean"}}},
             {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}},
             {"entities",
              list(
                  QJsonObject{
                      {"type", "object"},
                      {"properties",
                       QJsonObject{{"body", stableId()},
                                   {"kind", QJsonObject{{"type", "string"},
                                                        {"enum", QJsonArray{"context", "face",
                                                                            "edge", "guide"}}}},
                                   {"entity", stableId(true)}}},
                      {"required", QJsonArray{"body", "kind", "entity"}},
                      {"additionalProperties", false}},
                  1, 10000)}},
            {"entities"}),
        spec("geometry.delete", "Delete context", "Geometry", {{"body", stableId()}}, {"body"}),
        spec("asset.import", "Import managed asset bytes", "Assets",
             {{"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"mediaType", QJsonObject{{"type", "string"}, {"maxLength", 128}}},
              {"data", QJsonObject{{"type", "string"}, {"maxLength", 22369624}}}},
             {"name", "mediaType", "data"}),
        spec("asset.missing", "Record missing asset", "Assets",
             {{"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"mediaType", QJsonObject{{"type", "string"}, {"maxLength", 128}}}},
             {"name", "mediaType"}),
        spec("asset.replace", "Replace or resolve asset bytes", "Assets",
             {{"asset", stableId()},
              {"mediaType", QJsonObject{{"type", "string"}, {"maxLength", 128}}},
              {"data",
               QJsonObject{{"type", QJsonArray{"string", "null"}}, {"maxLength", 22369624}}}},
             {"asset", "data"}),
        spec("asset.delete", "Delete unused asset", "Assets", {{"asset", stableId()}}, {"asset"}),
        spec("material.create", "Create material swatch", "Materials",
             {{"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"color", list({{"type", "number"}, {"minimum", 0}, {"maximum", 1}}, 3, 3)},
              {"opacity", QJsonObject{{"type", "number"}, {"minimum", 0}, {"maximum", 1}}},
              {"asset", stableId(true)}},
             {"name", "color"}),
        spec("material.edit", "Edit material swatch", "Materials",
             {{"material", stableId()},
              {"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"color", list({{"type", "number"}, {"minimum", 0}, {"maximum", 1}}, 3, 3)},
              {"opacity", QJsonObject{{"type", "number"}, {"minimum", 0}, {"maximum", 1}}},
              {"asset", stableId(true)}},
             {"material"}),
        spec("material.delete", "Delete unused material", "Materials", {{"material", stableId()}},
             {"material"}),
        spec("material.assign", "Assign front/back material", "Materials",
             {{"body", stableId()},
              {"face", stableId()},
              {"material", stableId(true)},
              {"side",
               QJsonObject{{"type", "string"}, {"enum", QJsonArray{"front", "back", "both"}}}}},
             {"body", "material"}),
        textureMappingSpec(point, space),
        spec("material.color", "Paint selection", "Materials",
             {{"body", stableId()},
              {"color", list({{"type", "number"}, {"minimum", 0}, {"maximum", 1}}, 3, 3)}},
             {"body", "color"}),
        spec("group.create", "Make group from sibling contexts", "Scene",
             {{"members", list(stableId(), 1, 10000)},
              {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"members"}),
        spec("component.glue", "Set or clear the canonical component glue face", "Scene",
             {{"definition", stableId()},
              {"glue",
               QJsonObject{
                   {"type", QJsonArray{"object", "null"}},
                   {"properties", QJsonObject{{"member", stableId()},
                                              {"face", stableId()},
                                              {"anchor", point},
                                              {"tangent", point},
                                              {"cutsOpening", QJsonObject{{"type", "boolean"}}}}},
                   {"required", QJsonArray{"member", "face", "anchor", "tangent", "cutsOpening"}},
                   {"additionalProperties", false}}}},
             {"definition", "glue"}),
        spec("component.attach",
             "Place component on an ordinary host face; anchor, tangent and inset are host-local, "
             "angle is radians",
             "Scene",
             {{"body", stableId()},
              {"host", stableId()},
              {"face", stableId()},
              {"anchor", point},
              {"tangent", point},
              {"angle", number()},
              {"scale", point},
              {"inset", number()}},
             {"body", "host", "face", "anchor"}),
        spec(
            "component.bind",
            "Bind component at its current pose with explicit host-local normal inset", "Scene",
            {{"body", stableId()}, {"host", stableId()}, {"face", stableId()}, {"inset", number()}},
            {"body", "host", "face", "inset"}),
        spec("component.detach", "Detach component and restore its host opening", "Scene",
             {{"body", stableId()}}, {"body"}),
        spec("component.bake_host",
             "Retain host cut geometry and release all its component attachments", "Scene",
             {{"body", stableId()}}, {"body"}),
        spec("component.create", "Make component", "Scene",
             {{"body", stableId()}, {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"body"}),
        spec("component.instance", "Place component instance", "Scene",
             {{"definition", stableId()},
              {"matrix", list(number(), 16, 16)},
              {"parent", stableId(true)},
              {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"definition", "matrix"}),
        spec("component.make_unique", "Make component unique", "Scene", {{"body", stableId()}},
             {"body"}),
        spec("component.replace", "Replace component definition", "Scene",
             {{"body", stableId()}, {"definition", stableId()}}, {"body", "definition"}),
        spec("component.axes", "Change component local axes", "Scene",
             {{"definition", stableId()}, {"matrix", list(number(), 16, 16)}},
             {"definition", "matrix"}),
        spec("component.edit_instance", "Make one component instance unique and edit its geometry",
             "Scene",
             {{"body", stableId()}, {"commands", list(QJsonObject{{"type", "object"}}, 1, 100)}},
             {"body", "commands"}),
        spec("component.edit", "Edit shared component definition", "Scene",
             {{"definition", stableId()},
              {"instance", stableId()},
              {"commands", list(QJsonObject{{"type", "object"}}, 1, 100)}},
             {"definition", "commands"}),
        spec("geometry.merge_context", "Merge raw geometry in editing context", "Geometry",
             {{"context", stableId(true)}, {"members", list(stableId(), 0, 10000)}}, {"context"}),
        spec("group.explode", "Explode group", "Scene",
             {{"body", stableId()}, {"merge", QJsonObject{{"type", "boolean"}}}}, {"body"}),
        spec("entity.position", "Set entity origin", "Scene",
             {{"body", stableId()},
              {"position", point},
              {"frame", QJsonObject{{"type", "string"},
                                    {"enum", QJsonArray{"world", "parent"}},
                                    {"default", "world"}}}},
             {"body", "position"}),
        spec("entity.dimensions", "Set entity bounds dimensions", "Scene",
             {{"body", stableId()},
              {"dimensions", point},
              {"frame", QJsonObject{{"type", "string"},
                                    {"enum", QJsonArray{"world", "parent"}},
                                    {"default", "world"}}}},
             {"body", "dimensions"}),
        spec("entity.properties", "Replace semantic entity properties", "Scene",
             {{"body", stableId()},
              {"values",
               QJsonObject{{"type", "object"},
                           {"maxProperties", 128},
                           {"propertyNames", QJsonObject{{"minLength", 1}, {"maxLength", 128}}},
                           {"additionalProperties",
                            QJsonObject{{"type", QJsonArray{"boolean", "number", "string"}},
                                        {"maxLength", 2048}}}}}},
             {"body", "values"}),
        spec("scene.reparent", "Reparent and preserve world placement", "Scene",
             {{"body", stableId()}, {"parent", stableId(true)}}, {"body", "parent"}),
        spec("scene.state", "Set persistent visibility and lock", "Scene",
             {{"body", stableId(true)},
              {"hidden", QJsonObject{{"type", "boolean"}}},
              {"locked", QJsonObject{{"type", "boolean"}}}},
             {"body"}),
        spec("scene.transform", "Set object transform", "Scene",
             {{"body", stableId()}, {"matrix", list(number(), 16, 16)}, {"parent", stableId(true)}},
             {"body", "matrix"})};
}
QJsonObject commandDescription(const QString &name) {
    for (const auto &item : commandCatalog()) {
        const auto command = item.toObject();
        if (command["name"] == name)
            return command;
    }
    throw std::runtime_error("Unavailable command");
}
} // namespace sketchy
