#include "automation/commands.hpp"
namespace sketchy {
namespace {
QJsonObject number() { return {{"type", "number"}}; }
QJsonObject stableId(bool zero = false) {
    return {{"type", "string"},
            {"pattern", zero ? "^(0|[1-9][0-9]*)$" : "^[1-9][0-9]*$"},
            {"maxLength", 20},
            {"description", "Canonical uint64 decimal string"}};
}
QJsonObject list(QJsonObject items, int minimum, int maximum) {
    return {{"type", "array"}, {"items", items}, {"minItems", minimum}, {"maxItems", maximum}};
}
QJsonObject spec(QString name, QString label, QString category, QJsonObject properties,
                 QJsonArray required) {
    properties["command"] = QJsonObject{{"const", name}};
    required.append("command");
    return {{"name", name},
            {"label", label},
            {"category", category},
            {"parameters", QJsonObject{{"$schema", "https://json-schema.org/draft/2020-12/schema"},
                                       {"type", "object"},
                                       {"properties", properties},
                                       {"required", required},
                                       {"additionalProperties", false}}},
            {"validation", "Schema plus authoritative geometry, document and resource validation"},
            {"undo", "one batch history item"}};
}
} // namespace
QJsonArray commandCatalog() {
    auto coordinate = QJsonObject{
        {"type", "number"}, {"minimum", -coordinateLimit}, {"maximum", coordinateLimit}};
    auto point = list(coordinate, 3, 3);
    const QJsonObject space{{"type", "string"}, {"enum", QJsonArray{"local", "world"}}};
    return {
        spec("guide.point", "Create guide point", "Guides",
             {{"body", stableId(true)}, {"space", space}, {"origin", point}}, {"body", "origin"}),
        spec("guide.line", "Create guide line", "Guides",
             {{"body", stableId(true)}, {"space", space}, {"origin", point}, {"direction", point}},
             {"body", "origin", "direction"}),
        spec("guide.angle", "Create angled guide", "Guides",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"angle", number()}},
             {"body", "origin", "normal", "xAxis", "angle"}),
        spec("guide.offset", "Offset guide line", "Guides",
             {{"body", stableId()},
              {"space", space},
              {"guide", stableId()},
              {"normal", point},
              {"distance", number()}},
             {"body", "guide", "normal", "distance"}),
        spec("guide.erase", "Delete guide", "Guides", {{"body", stableId()}, {"guide", stableId()}},
             {"body", "guide"}),
        spec("guide.clear", "Delete guides in context or document", "Guides",
             {{"body", stableId(true)}}, {"body"}),
        spec("geometry.face", "Draw face", "Geometry",
             {{"loops", list(list(point, 3, 10000), 1, 10000)},
              {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"loops"}),
        spec("geometry.insert_edges", "Insert planar edges and form faces", "Geometry",
             {{"body", stableId(true)},
              {"origin", point},
              {"normal", point},
              {"edges", list(list(point, 2, 2), 1, 1024)}},
             {"body", "origin", "normal", "edges"}),
        spec("geometry.rectangle", "Draw rectangle on plane", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"width", number()},
              {"height", number()}},
             {"body", "origin", "normal", "xAxis", "width", "height"}),
        spec("geometry.polygon", "Draw regular polygon", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"sides", QJsonObject{{"type", "integer"}, {"minimum", 3}, {"maximum", 256}}}},
             {"body", "origin", "normal", "xAxis", "radius", "sides"}),
        spec("geometry.polyline", "Draw sampled polyline", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"points", list(point, 2, 512)},
              {"closed", QJsonObject{{"type", "boolean"}}}},
             {"body", "origin", "normal", "points", "closed"}),
        spec("geometry.circle", "Draw circle", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 3}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "segments"}),
        spec("geometry.arc_center", "Draw center arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"startAngle", number()},
              {"sweepAngle", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "startAngle", "sweepAngle",
              "segments"}),
        spec("geometry.arc_two_points", "Draw two-point arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"start", point},
              {"end", point},
              {"normal", point},
              {"bulge", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "start", "end", "normal", "bulge", "segments"}),
        spec("geometry.arc_three_points", "Draw three-point arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"start", point},
              {"through", point},
              {"end", point},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "start", "through", "end", "segments"}),
        spec("geometry.pie", "Draw pie sector", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"startAngle", number()},
              {"sweepAngle", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 2}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "startAngle", "sweepAngle",
              "segments"}),
        spec("geometry.wire", "Draw loose edge", "Geometry",
             {{"body", stableId(true)}, {"start", point}, {"end", point}},
             {"body", "start", "end"}),
        spec("geometry.split_edge", "Split edge", "Geometry",
             {{"body", stableId()},
              {"edge", stableId()},
              {"fraction",
               QJsonObject{{"type", "number"}, {"exclusiveMinimum", 0}, {"exclusiveMaximum", 1}}}},
             {"body", "edge", "fraction"}),
        spec("geometry.erase_face", "Erase face, retain boundary", "Geometry",
             {{"body", stableId()}, {"face", stableId()}}, {"body", "face"}),
        spec("geometry.erase_edge", "Erase edge or join coplanar faces", "Geometry",
             {{"body", stableId()}, {"edge", stableId()}}, {"body", "edge"}),
        spec("geometry.heal_face", "Heal closed planar region", "Geometry",
             {{"body", stableId()}, {"edge", stableId()}, {"origin", point}, {"normal", point}},
             {"body", "edge", "origin", "normal"}),
        spec("geometry.cleanup", "Merge coincident topology", "Geometry", {{"body", stableId()}},
             {"body"}),
        spec("geometry.push_pull", "Push/pull selected face", "Geometry",
             {{"body", stableId()},
              {"face", stableId()},
              {"distance", number()},
              {"newFace", QJsonObject{{"type", "boolean"}, {"default", false}}}},
             {"body", "face", "distance"}),
        spec("geometry.extrude_isolated", "Extrude isolated face", "Geometry",
             {{"body", stableId()}, {"face", stableId()}, {"distance", number()}},
             {"body", "face", "distance"}),
        spec("geometry.transform_selection", "Transform selected geometry", "Geometry",
             {{"entities",
               list(QJsonObject{{"type", "object"},
                                {"properties",
                                 QJsonObject{
                                     {"body", stableId()},
                                     {"entity", stableId(true)},
                                     {"kind",
                                      QJsonObject{{"type", "string"},
                                                  {"enum", QJsonArray{"context", "face", "edge",
                                                                      "vertex", "guide"}}}}}},
                                {"required", QJsonArray{"body", "kind", "entity"}},
                                {"additionalProperties", false}},
                    1, 10000)},
              {"matrix", list(number(), 16, 16)},
              {"pivot", point},
              {"space", space},
              {"copy", QJsonObject{{"type", "boolean"}, {"default", false}}}},
             {"entities", "matrix"}),
        spec("geometry.translate", "Move selection", "Geometry",
             {{"body", stableId()}, {"delta", point}}, {"body", "delta"}),
        spec(
            "geometry.erase_selection", "Delete selected entities", "Geometry",
            {{"entities",
              list(
                  QJsonObject{
                      {"type", "object"},
                      {"properties",
                       QJsonObject{{"body", stableId()},
                                   {"kind", QJsonObject{{"type", "string"},
                                                        {"enum", QJsonArray{"context", "face",
                                                                            "edge", "guide"}}}},
                                   {"entity", stableId(true)}}},
                      {"required", QJsonArray{"body", "kind", "entity"}},
                      {"additionalProperties", false}},
                  1, 10000)}},
            {"entities"}),
        spec("geometry.delete", "Delete context", "Geometry", {{"body", stableId()}}, {"body"}),
        spec("material.color", "Paint selection", "Materials",
             {{"body", stableId()},
              {"color", list({{"type", "number"}, {"minimum", 0}, {"maximum", 1}}, 3, 3)}},
             {"body", "color"}),
        spec("scene.transform", "Set object transform", "Scene",
             {{"body", stableId()}, {"matrix", list(number(), 16, 16)}, {"parent", stableId(true)}},
             {"body", "matrix"})};
}
QJsonObject commandDescription(const QString &name) {
    for (const auto &item : commandCatalog()) {
        const auto command = item.toObject();
        if (command["name"] == name)
            return command;
    }
    throw std::runtime_error("Unavailable command");
}
} // namespace sketchy
