#include "automation/commands.hpp"
#include "core/copy_array.hpp"
namespace sketchy {
namespace {
QJsonObject number() { return {{"type", "number"}}; }
QJsonObject stableId(bool zero = false) {
    return {{"type", "string"},
            {"pattern", zero ? "^(0|[1-9][0-9]*)$" : "^[1-9][0-9]*$"},
            {"maxLength", 20},
            {"description", "Canonical uint64 decimal string"}};
}
QJsonObject list(QJsonObject items, int minimum, int maximum) {
    return {{"type", "array"}, {"items", items}, {"minItems", minimum}, {"maxItems", maximum}};
}
QJsonObject targetsSchema() {
    return list(
        QJsonObject{{"type", "object"},
                    {"properties",
                     QJsonObject{{"body", stableId()},
                                 {"entity", stableId(true)},
                                 {"kind", QJsonObject{{"type", "string"},
                                                      {"enum", QJsonArray{"context", "face", "edge",
                                                                          "vertex", "guide"}}}}}},
                    {"required", QJsonArray{"body", "kind", "entity"}},
                    {"additionalProperties", false}},
        1, 10000);
}
QJsonObject spec(QString name, QString label, QString category, QJsonObject properties,
                 QJsonArray required) {
    properties["command"] = QJsonObject{{"const", name}};
    required.append("command");
    return {{"name", name},
            {"label", label},
            {"category", category},
            {"parameters", QJsonObject{{"$schema", "https://json-schema.org/draft/2020-12/schema"},
                                       {"type", "object"},
                                       {"properties", properties},
                                       {"required", required},
                                       {"additionalProperties", false}}},
            {"validation", "Schema plus authoritative geometry, document and resource validation"},
            {"undo", "one batch history item"}};
}
} // namespace
QJsonArray commandCatalog() {
    auto coordinate = QJsonObject{
        {"type", "number"}, {"minimum", -coordinateLimit}, {"maximum", coordinateLimit}};
    auto point = list(coordinate, 3, 3);
    const QJsonObject space{{"type", "string"}, {"enum", QJsonArray{"local", "world"}}};
    return {
        spec("tag.create", "Create tag or folder", "Organization",
             {{"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"parent", stableId(true)},
              {"folder", QJsonObject{{"type", "boolean"}}}},
             {"name"}),
        spec("tag.edit", "Rename, move or show tag", "Organization",
             {{"tag", stableId()},
              {"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"parent", stableId(true)},
              {"visible", QJsonObject{{"type", "boolean"}}}},
             {"tag"}),
        spec("tag.delete", "Delete unused tag or empty folder", "Organization",
             {{"tag", stableId()}}, {"tag"}),
        spec("tag.assign", "Assign entity tag", "Organization",
             {{"body", stableId()}, {"tag", stableId(true)}}, {"body", "tag"}),
        spec("scene.rename", "Rename entity", "Scene",
             {{"body", stableId()}, {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"body", "name"}),
        spec("guide.point", "Create guide point", "Guides",
             {{"body", stableId(true)}, {"space", space}, {"origin", point}}, {"body", "origin"}),
        spec("guide.line", "Create guide line", "Guides",
             {{"body", stableId(true)}, {"space", space}, {"origin", point}, {"direction", point}},
             {"body", "origin", "direction"}),
        spec("guide.angle", "Create angled guide", "Guides",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"angle", number()}},
             {"body", "origin", "normal", "xAxis", "angle"}),
        spec("guide.offset", "Offset guide line", "Guides",
             {{"body", stableId()},
              {"space", space},
              {"guide", stableId()},
              {"normal", point},
              {"distance", number()}},
             {"body", "guide", "normal", "distance"}),
        spec("guide.erase", "Delete guide", "Guides", {{"body", stableId()}, {"guide", stableId()}},
             {"body", "guide"}),
        spec("guide.clear", "Delete guides in context or document", "Guides",
             {{"body", stableId(true)}}, {"body"}),
        spec("geometry.face", "Draw face", "Geometry",
             {{"loops", list(list(point, 3, 10000), 1, 10000)},
              {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"loops"}),
        spec("geometry.insert_edges", "Insert planar edges and form faces", "Geometry",
             {{"body", stableId(true)},
              {"origin", point},
              {"normal", point},
              {"edges", list(list(point, 2, 2), 1, 1024)}},
             {"body", "origin", "normal", "edges"}),
        spec("geometry.rectangle", "Draw rectangle on plane", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"width", number()},
              {"height", number()}},
             {"body", "origin", "normal", "xAxis", "width", "height"}),
        spec("geometry.polygon", "Draw regular polygon", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"sides", QJsonObject{{"type", "integer"}, {"minimum", 3}, {"maximum", 256}}}},
             {"body", "origin", "normal", "xAxis", "radius", "sides"}),
        spec("geometry.polyline", "Draw sampled polyline", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"origin", point},
              {"normal", point},
              {"points", list(point, 2, 512)},
              {"closed", QJsonObject{{"type", "boolean"}}}},
             {"body", "origin", "normal", "points", "closed"}),
        spec("geometry.circle", "Draw circle", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 3}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "segments"}),
        spec("geometry.arc_center", "Draw center arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"startAngle", number()},
              {"sweepAngle", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "startAngle", "sweepAngle",
              "segments"}),
        spec("geometry.arc_two_points", "Draw two-point arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"start", point},
              {"end", point},
              {"normal", point},
              {"bulge", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "start", "end", "normal", "bulge", "segments"}),
        spec("geometry.arc_three_points", "Draw three-point arc", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"start", point},
              {"through", point},
              {"end", point},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 1}, {"maximum", 256}}}},
             {"body", "start", "through", "end", "segments"}),
        spec("geometry.pie", "Draw pie sector", "Geometry",
             {{"body", stableId(true)},
              {"space", space},
              {"center", point},
              {"normal", point},
              {"xAxis", point},
              {"radius", number()},
              {"startAngle", number()},
              {"sweepAngle", number()},
              {"segments", QJsonObject{{"type", "integer"}, {"minimum", 2}, {"maximum", 256}}}},
             {"body", "center", "normal", "xAxis", "radius", "startAngle", "sweepAngle",
              "segments"}),
        spec("geometry.wire", "Draw loose edge", "Geometry",
             {{"body", stableId(true)}, {"start", point}, {"end", point}},
             {"body", "start", "end"}),
        spec("geometry.split_edge", "Split edge", "Geometry",
             {{"body", stableId()},
              {"edge", stableId()},
              {"fraction",
               QJsonObject{{"type", "number"}, {"exclusiveMinimum", 0}, {"exclusiveMaximum", 1}}}},
             {"body", "edge", "fraction"}),
        spec("geometry.erase_face", "Erase face, retain boundary", "Geometry",
             {{"body", stableId()}, {"face", stableId()}}, {"body", "face"}),
        spec("geometry.erase_edge", "Erase edge or join coplanar faces", "Geometry",
             {{"body", stableId()}, {"edge", stableId()}}, {"body", "edge"}),
        spec("geometry.heal_face", "Heal closed planar region", "Geometry",
             {{"body", stableId()}, {"edge", stableId()}, {"origin", point}, {"normal", point}},
             {"body", "edge", "origin", "normal"}),
        spec("geometry.cleanup", "Merge coincident topology", "Geometry", {{"body", stableId()}},
             {"body"}),
        spec("geometry.push_pull", "Push/pull selected face", "Geometry",
             {{"body", stableId()},
              {"face", stableId()},
              {"distance", number()},
              {"newFace", QJsonObject{{"type", "boolean"}, {"default", false}}}},
             {"body", "face", "distance"}),
        spec("geometry.extrude_isolated", "Extrude isolated face", "Geometry",
             {{"body", stableId()}, {"face", stableId()}, {"distance", number()}},
             {"body", "face", "distance"}),
        spec("geometry.transform_selection", "Transform selected geometry", "Geometry",
             {{"entities", targetsSchema()},
              {"matrix", list(number(), 16, 16)},
              {"pivot", point},
              {"space", space},
              {"copy", QJsonObject{{"type", "boolean"}, {"default", false}}}},
             {"entities", "matrix"}),
        spec("geometry.array_selection", "Linear or radial copy array", "Geometry",
             {{"entities", targetsSchema()},
              {"mode", QJsonObject{{"type", "string"}, {"enum", QJsonArray{"linear", "radial"}}}},
              {"count", QJsonObject{{"type", "integer"},
                                    {"minimum", 1},
                                    {"maximum", int(maxArrayCopies)},
                                    {"description",
                                     "New copies; total instances including source = count + 1"}}},
              {"delta", point},
              {"axis", point},
              {"angle", number()},
              {"pivot", point},
              {"space", space},
              {"divide",
               QJsonObject{
                   {"type", "boolean"},
                   {"default", false},
                   {"description",
                    "Divide displacement or sweep into count intervals, including endpoint"}}}},
             {"entities", "mode", "count"}),
        spec("geometry.translate", "Move selection", "Geometry",
             {{"body", stableId()}, {"delta", point}}, {"body", "delta"}),
        spec("geometry.erase_selection", "Delete selected entities", "Geometry",
             {{"context", stableId(true)},
              {"showHidden", QJsonObject{{"type", "boolean"}}},
              {"entities",
               list(QJsonObject{{"type", "object"},
                                {"properties",
                                 QJsonObject{{"body", stableId()},
                                             {"kind",
                                              QJsonObject{{"type", "string"},
                                                          {"enum", QJsonArray{"context", "face",
                                                                              "edge", "guide"}}}},
                                             {"entity", stableId(true)}}},
                                {"required", QJsonArray{"body", "kind", "entity"}},
                                {"additionalProperties", false}},
                    1, 10000)}},
             {"entities"}),
        spec(
            "group.selection", "Make group from selected entities", "Scene",
            {{"context", stableId(true)},
             {"showHidden", QJsonObject{{"type", "boolean"}}},
             {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}},
             {"entities",
              list(
                  QJsonObject{
                      {"type", "object"},
                      {"properties",
                       QJsonObject{{"body", stableId()},
                                   {"kind", QJsonObject{{"type", "string"},
                                                        {"enum", QJsonArray{"context", "face",
                                                                            "edge", "guide"}}}},
                                   {"entity", stableId(true)}}},
                      {"required", QJsonArray{"body", "kind", "entity"}},
                      {"additionalProperties", false}},
                  1, 10000)}},
            {"entities"}),
        spec(
            "component.selection", "Make component from selected entities", "Scene",
            {{"context", stableId(true)},
             {"showHidden", QJsonObject{{"type", "boolean"}}},
             {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}},
             {"entities",
              list(
                  QJsonObject{
                      {"type", "object"},
                      {"properties",
                       QJsonObject{{"body", stableId()},
                                   {"kind", QJsonObject{{"type", "string"},
                                                        {"enum", QJsonArray{"context", "face",
                                                                            "edge", "guide"}}}},
                                   {"entity", stableId(true)}}},
                      {"required", QJsonArray{"body", "kind", "entity"}},
                      {"additionalProperties", false}},
                  1, 10000)}},
            {"entities"}),
        spec("geometry.delete", "Delete context", "Geometry", {{"body", stableId()}}, {"body"}),
        spec("asset.import", "Import managed asset bytes", "Assets",
             {{"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"mediaType", QJsonObject{{"type", "string"}, {"maxLength", 128}}},
              {"data", QJsonObject{{"type", "string"}, {"maxLength", 22369624}}}},
             {"name", "mediaType", "data"}),
        spec("asset.missing", "Record missing asset", "Assets",
             {{"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"mediaType", QJsonObject{{"type", "string"}, {"maxLength", 128}}}},
             {"name", "mediaType"}),
        spec("asset.replace", "Replace or resolve asset bytes", "Assets",
             {{"asset", stableId()},
              {"mediaType", QJsonObject{{"type", "string"}, {"maxLength", 128}}},
              {"data",
               QJsonObject{{"type", QJsonArray{"string", "null"}}, {"maxLength", 22369624}}}},
             {"asset", "data"}),
        spec("asset.delete", "Delete unused asset", "Assets", {{"asset", stableId()}}, {"asset"}),
        spec("material.create", "Create material swatch", "Materials",
             {{"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"color", list({{"type", "number"}, {"minimum", 0}, {"maximum", 1}}, 3, 3)},
              {"opacity", QJsonObject{{"type", "number"}, {"minimum", 0}, {"maximum", 1}}},
              {"asset", stableId(true)}},
             {"name", "color"}),
        spec("material.edit", "Edit material swatch", "Materials",
             {{"material", stableId()},
              {"name", QJsonObject{{"type", "string"}, {"minLength", 1}, {"maxLength", 1024}}},
              {"color", list({{"type", "number"}, {"minimum", 0}, {"maximum", 1}}, 3, 3)},
              {"opacity", QJsonObject{{"type", "number"}, {"minimum", 0}, {"maximum", 1}}},
              {"asset", stableId(true)}},
             {"material"}),
        spec("material.delete", "Delete unused material", "Materials", {{"material", stableId()}},
             {"material"}),
        spec("material.assign", "Assign front/back material", "Materials",
             {{"body", stableId()},
              {"face", stableId()},
              {"material", stableId(true)},
              {"side",
               QJsonObject{{"type", "string"}, {"enum", QJsonArray{"front", "back", "both"}}}}},
             {"body", "material"}),
        spec("material.color", "Paint selection", "Materials",
             {{"body", stableId()},
              {"color", list({{"type", "number"}, {"minimum", 0}, {"maximum", 1}}, 3, 3)}},
             {"body", "color"}),
        spec("group.create", "Make group from sibling contexts", "Scene",
             {{"members", list(stableId(), 1, 10000)},
              {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"members"}),
        spec("component.create", "Make component", "Scene",
             {{"body", stableId()}, {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"body"}),
        spec("component.instance", "Place component instance", "Scene",
             {{"definition", stableId()},
              {"matrix", list(number(), 16, 16)},
              {"parent", stableId(true)},
              {"name", QJsonObject{{"type", "string"}, {"maxLength", 1024}}}},
             {"definition", "matrix"}),
        spec("component.make_unique", "Make component unique", "Scene", {{"body", stableId()}},
             {"body"}),
        spec("component.replace", "Replace component definition", "Scene",
             {{"body", stableId()}, {"definition", stableId()}}, {"body", "definition"}),
        spec("component.axes", "Change component local axes", "Scene",
             {{"definition", stableId()}, {"matrix", list(number(), 16, 16)}},
             {"definition", "matrix"}),
        spec("component.edit", "Edit shared component definition", "Scene",
             {{"definition", stableId()},
              {"instance", stableId()},
              {"commands", list(QJsonObject{{"type", "object"}}, 1, 100)}},
             {"definition", "commands"}),
        spec("geometry.merge_context", "Merge raw geometry in editing context", "Geometry",
             {{"context", stableId(true)}, {"members", list(stableId(), 0, 10000)}}, {"context"}),
        spec("group.explode", "Explode group", "Scene",
             {{"body", stableId()}, {"merge", QJsonObject{{"type", "boolean"}}}}, {"body"}),
        spec("entity.position", "Set entity origin", "Scene",
             {{"body", stableId()},
              {"position", point},
              {"frame", QJsonObject{{"type", "string"},
                                    {"enum", QJsonArray{"world", "parent"}},
                                    {"default", "world"}}}},
             {"body", "position"}),
        spec("entity.dimensions", "Set entity bounds dimensions", "Scene",
             {{"body", stableId()},
              {"dimensions", point},
              {"frame", QJsonObject{{"type", "string"},
                                    {"enum", QJsonArray{"world", "parent"}},
                                    {"default", "world"}}}},
             {"body", "dimensions"}),
        spec("entity.properties", "Replace semantic entity properties", "Scene",
             {{"body", stableId()},
              {"values",
               QJsonObject{{"type", "object"},
                           {"maxProperties", 128},
                           {"propertyNames", QJsonObject{{"minLength", 1}, {"maxLength", 128}}},
                           {"additionalProperties",
                            QJsonObject{{"type", QJsonArray{"boolean", "number", "string"}},
                                        {"maxLength", 2048}}}}}},
             {"body", "values"}),
        spec("scene.reparent", "Reparent and preserve world placement", "Scene",
             {{"body", stableId()}, {"parent", stableId(true)}}, {"body", "parent"}),
        spec("scene.state", "Set persistent visibility and lock", "Scene",
             {{"body", stableId(true)},
              {"hidden", QJsonObject{{"type", "boolean"}}},
              {"locked", QJsonObject{{"type", "boolean"}}}},
             {"body"}),
        spec("scene.transform", "Set object transform", "Scene",
             {{"body", stableId()}, {"matrix", list(number(), 16, 16)}, {"parent", stableId(true)}},
             {"body", "matrix"})};
}
QJsonObject commandDescription(const QString &name) {
    for (const auto &item : commandCatalog()) {
        const auto command = item.toObject();
        if (command["name"] == name)
            return command;
    }
    throw std::runtime_error("Unavailable command");
}
} // namespace sketchy
