"""Regenerate independent reference drawings with ezdxf 1.4.4 (test tooling only)."""
import pathlib
import sys
import ezdxf
assert ezdxf.__version__ == '1.4.4'
out = pathlib.Path(sys.argv[1])
out.mkdir(parents=True, exist_ok=True)
for version in ['R12', 'R2018']:
    doc = ezdxf.new(version)
    if version != 'R12':
        doc.units = 4
    layer = doc.layers.new('Walls', dxfattribs={'color': 7})
    layer.off()
    layer.freeze()
    layer.lock()
    doc.layers.new('Curves')
    model = doc.modelspace()
    model.add_line((0, 0), (6000, 4000), dxfattribs={'layer': 'Walls'})
    model.add_arc((1000, 2000), 1000, 350, 10, dxfattribs={'layer': 'Curves'})
    model.add_circle((3000, 3000), 500, dxfattribs={'layer': 'Curves'})
    if version == 'R12':
        model.add_polyline2d([(0, 0), (2000, 0), (2000, 2000)], close=True,
                             dxfattribs={'layer': 'Curves'})
    else:
        model.add_lwpolyline([(0, 0, 1), (2000, 0, 0), (2000, 2000, 0)],
                             format='xyb', close=True, dxfattribs={'layer': 'Curves'})
    model.add_text('Unsupported reference note')
    doc.layout().add_line((10000, 10000), (20000, 20000))
    doc.saveas(out / ('ezdxf-' + version.lower() + '.dxf'))
print('Independent DXF fixtures generated by', ezdxf.__version__)
