#!/usr/bin/env python3
"""Generate installed reference artifacts from the running engine's registries.

Use --check in CI; generation never hand-maintains command names or schemas.
Only the Python standard library is required, at build/verification time.
"""
import argparse
import json
from pathlib import Path
import subprocess


def discover(cli, option):
    result = subprocess.run([str(cli), option], capture_output=True, check=True,
                            text=True, timeout=30)
    return json.loads(result.stdout)


def render(cli):
    core = discover(cli, '--capabilities')
    session = discover(cli, '--session-capabilities')
    mcp = discover(cli, '--mcp-capabilities')
    reference = {
        'referenceVersion': 1,
        'apiVersion': core['apiVersion'],
        'units': core['units'], 'up': core['up'],
        'commands': core['commandSchemas'],
        'inspection': core['inspection']['queries'],
        'transactions': core['transactions']['operations'],
        'session': session['operations'],
        'mcpProtocolVersion': mcp['protocolVersion'], 'mcpTools': mcp['tools'],
        'recipe': discover(cli, '--recipe-capabilities'),
        'extensions': discover(cli, '--extension-capabilities'),
    }
    lines = [
        '# Generated tool reference', '',
        'Generated by `scripts/generate-tool-reference.py` from the running engine.',
        'Do not edit this file or its [machine-readable schemas](api/tool-reference-v1.json)',
        'by hand. CI compares both artifacts with the live registries.', '',
        'API version: **1**. Lengths use metres, angles use radians, and Z is up.',
        'Canonical decimal strings carry entity IDs and revisions without precision loss.',
        'Parameter schemas include bounds, required fields, and additional-property rules.',
        'Schema acceptance does not replace authoritative geometry/resource validation.', '',
        'Commands run inside an atomic batch or staged transaction. Inspect the draft,',
        'check measurements, then commit the sealed payload against the expected revision.',
        'Use the [agent guide](AI_MODELING.md) for targeting and outcome reconciliation.', '',
    ]
    for key, title in [('commands', 'Model commands'), ('inspection', 'Bounded queries'),
                       ('transactions', 'Transactions'), ('session', 'Session operations'),
                       ('mcpTools', 'MCP tools')]:
        entries = reference[key]
        assert isinstance(entries, list) and entries, key
        lines += [f'## {title}', '', '| Name | Purpose | Required parameters |',
                  '| --- | --- | --- |']
        for entry in entries:
            # Some session operations are described as names; schemas for their
            # shared query/transaction calls are in the corresponding registries.
            if isinstance(entry, str):
                name, purpose, required = entry, '', []
            else:
                name = entry['name']
                schema = entry.get('parameters', entry.get('inputSchema', {}))
                purpose = entry.get('label', entry.get('description', ''))
                required = schema.get('required', [])
            purpose = ' '.join(purpose.split()).replace('|', '&#124;')
            lines.append(f'| `{name}` | {purpose} | ' +
                         ', '.join(f'`{field}`' for field in required) + ' |')
        lines += ['']
    lines += ['## Versioned discovery', '',
              '`--capabilities`, `--session-capabilities`, `--mcp-capabilities`,',
              '`--recipe-capabilities` and `--extension-capabilities` return these',
              'registries without opening a model or contacting a provider.',
              'A catalog describes API support; it does not prove a runtime dependency',
              'is installed or that a provider has an authenticated session.', '']
    return {'docs/api/tool-reference-v1.json': json.dumps(reference, indent=2,
                                                        sort_keys=True) + '\n',
            'docs/TOOL_REFERENCE.md': '\n'.join(lines)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cli', type=Path, required=True)
    parser.add_argument('--root', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    artifacts = render(args.cli.resolve())
    for relative, content in artifacts.items():
        path = args.root / relative
        if args.check:
            if not path.is_file() or path.read_bytes() != content.encode():
                raise SystemExit(f'Registry/reference drift: regenerate {relative}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content.encode())
    print(f'{len(artifacts)} generated reference artifacts ' +
          ('match the live registries' if args.check else 'written'))


if __name__ == '__main__':
    main()
